### ISSUE TITLE
AWS_PROFILE environment variable ignored when loading credentials.

### ISSUE THREAD

**Issue by ortimanu** [grails-aws/grails-aws#47]
Hello,

I have several credentials inside my `~/.aws/credentials` file in addition to my default ones. This file looks like this:

```
[default]
aws_access_key_id = ************
aws_secret_access_key = ************

[company1]
aws_access_key_id = ************
aws_secret_access_key = ************

[company2]
aws_access_key_id = ************
aws_secret_access_key = ************
```

As can be seen, I have different Grails projects that use different AWS accounts I manage for different companies. Therefore, instead of specifying the credentials in the config.groovy file for each project, I would like to be able to run the project and configure the `AWS_PROFILE` environment variable before running it so that the AWS Credentials Provider Chain will use the credentials provided in said credentials file. That would help me a lot since this way I specify my credentials in a centralized way instead of in each application.

The provider chain only picks up my `[default]` profile even though I configured the `AWS_PROFILE` env variable to use the `[company1]` profile. Therefore, it is ignoring this environment variable and always using the default one.

I think the plugin is ignoring this env var in some way since when using the AWS Java SDK separately it works. Maybe I have something wrong. A nice solution would be to specify the profile in a plugin config property in the `config.groovy` file.

**Comment by j4y** [comment]
This was added to the AWS Java SDK in version 1.8.11 

http://aws.amazon.com/releasenotes/Java/6786824462413999

**Comment by ortimanu** [comment]
Is there any ETA for when the grails-aws will be upgraded to sdk 1.8.11?

**Comment by j4y** [comment]
I just upgraded to 1.9.13 and released a new version of the plugin:

`compile ":aws:1.9.13.0"`

**Comment by ortimanu** [comment]
Version `.1.9.13.0` solved the problem. Thanks!
