### ISSUE TITLE
TransferManager.shutdownNow() does not work

### ISSUE THREAD

**Issue by ortimanu** [grails-aws/grails-aws#48]
Hello! I am experiencing the same problem described on this AWS forum post: https://forums.aws.amazon.com/thread.jspa?messageID=593757. As I described it there: 

>  I have a web app that uses TransferManager from server side to upload some files. When I use `transferManager.shutdownNow()` it gives me the RejectedExecutionException. When I do not shutdown the TransferManager, then it stops working after a 1000 threads are opened. 

This is causing huge issues in my `Grails` app which I am struggling to solve. I read some of the code from the plugin's `AmazonWebService.groovy` file and in its `getTransferManager` method I realized that you are getting the `TransferManager` "singleton" from a list with the `regionName` as the key. Therefore, I think that when the `TransferManager` is shutdown with `transferManager.shutdownNow()` method and I retrieve it again on a next iteration, the `TransferManager`'s instance is already down. 

Can you think of any elegant way to prevent this without having to always create a new `TransferManager` instance using `new TransferManager(getS3(regionName))` as it is done right now in the `AmazonWebService.groovy` file?

**Comment by j4y** [comment]
This issue should be opened with the AWS java SDK project.
