### ISSUE TITLE
regular configuration won't send ses

### ISSUE THREAD

**Issue by t2developer** [grails-aws/grails-aws#49]
I don't know why I can't get SES to work. I got S3 to work just fine. 

I'm getting this error:
Error creating bean with name 'sendSesMail': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'region' of bean class [grails.plugin.aws.ses.SendSesMail]: Bean property 'region' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at grails.plugin.aws.util.MetaClassInjector$_injectSesMethods_closure4_closure5.doCall(MetaClassInjector.groovy:74)

here is my config:
aws {
		   credentials {
			  accessKey = "xxxx"
			  secretKey = "xxx"
		   }
		   s3 {
			   bucket = "xxx2"
			   bucketLocation = "Northern California"
			   acl = "private"
			}
		   ses {
			   enabled = true
//			   catchall = "allmailforme@gmail.com"
			   from = "system@xxxxxxxxx.com"
			   region = "US_WEST_2"  
			}
		}

calling it from my service:
		d
ef mailId = sesMail{
			to "me@myemail.com"
			subject "test plain text mail"
			body "this is the e-mail content, sent at: (${new Date().format('dd/MM/yyyy HH:mm')})"
		}

**Comment by v1p** [comment]
@t2developer : Can you gist a stacktrace for this issue ?

**Comment by j4y** [comment]
I believe this has been fixed.  If you can reproduce this with the newest version of the plugin, please respond.
