### ISSUE TITLE
Conversion to Grails 3.0 Plugin Architecture

### ISSUE THREAD

**Issue by ortimanu** [grails-aws/grails-aws#50]
If there is a plugin I would like to see migrated to Grails 3.0 its this one! I think I use this plugin in all my projects! Are there any plans to migrate/upgrade to Grails 3? Here are some examples of existing Grails 3 plugins: [https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fgrails3-plugins%2F&sa=D&sntz=1&usg=AFQjCNHNOojpI3eMW8odZ4K-YNTFpNdX9g](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fgrails3-plugins%2F&sa=D&sntz=1&usg=AFQjCNHNOojpI3eMW8odZ4K-YNTFpNdX9g)

**Comment by bostanio** [comment]
A pull request would be appreciated.

**Comment by j4y** [comment]
I created a branch for grails `3.0.7` and as you would expect -- it fails:

https://travis-ci.org/grails-aws/grails-aws/branches

**Comment by ctoestreich** [comment]
I completed the initial pass of this for S3 functionality.

https://github.com/grails-aws/grails-aws/pull/58
