### ISSUE TITLE
Could not find artifact org.grails.plugins:aws:jar:1.9.13.4 in grailsCentral

### ISSUE THREAD

**Issue by Omnipresent** [grails-aws/grails-aws#59]
I am trying to use this plugin in grails `2.3.5` but I keep getting error `compile "org.grails.plugins:aws:1.9.13.4"`

I have `compile "org.grails.plugins:aws:1.9.13.4"` in dependencies in my `BuildConfig.groovy`

**Comment by j4y** [comment]
Try adding it in the plugins section of `BuildConfig.groovy`
```
    plugins {
        compile ":aws:1.9.13.4"
```

**Comment by Omnipresent** [comment]
Thanks!
